# Generated by Django 3.2.25 on 2025-07-06 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVImportStub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Импорт CSV',
                'verbose_name_plural': 'Импорт CSV',
            },
        ),
        migrations.CreateModel(
            name='ImportProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_success_row', models.IntegerField(default=0)),
                ('images_downloaded', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('idle', 'Ожидание'), ('running', 'Выполняется'), ('paused', 'Пауза'), ('waiting', 'Ожидание паузы'), ('stopped', 'Остановлено'), ('error', 'Ошибка'), ('completed', 'Завершено')], default='idle', max_length=16)),
                ('pause_until', models.DateTimeField(blank=True, null=True)),
                ('pause_minutes', models.IntegerField(default=10)),
                ('extra_delay_after_429', models.IntegerField(default=0)),
                ('last_message', models.TextField(blank=True, default='')),
                ('stopped_by_user', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
