# Generated by Django 3.2.25 on 2025-07-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAdCrawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importprogress',
            name='total_rows',
            field=models.IntegerField(default=0),
        ),
    ]
