# Generated by Django 3.2.25 on 2025-07-08 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DjangoAdCrawler', '0002_importprogress_total_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importprogress',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
